name: midar
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_nfc_kit: ^3.3.3
  ndef: ^0.3.1
  nfc_manager: ^3.3.0
  blue_bird_scanner: ^2.0.1+5
  flutter_screenutil: ^5.9.0
  # blue_bird_scanner: ^2.0.1+5
  # dio: ^5.3.3
  # flutter_easyloading: ^3.0.5
  # get_storage: ^2.1.1
  # flutter_nfc_kit: ^3.3.3
  # ndef: ^0.3.1
  # nfc_classic_mifare: ^0.3.5

  # Useful utils
  # nb_utils: ^6.0.6
  # flutter_svg: ^2.0.7

  # mifare_nfc_classic: 
  #   git:
  #     url: https://github.com/PeterWahba/mifare_nfc_classic.git
      # https://github.com/MaldonadoAndres/mifare_nfc_classic.git
      # https://github.com/PeterWahba/mifare_nfc_classic.git

dev_dependencies: 
  flutter_lints: 2.0.3
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

